# Generated by Django 2.0.1 on 2020-06-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('bmi', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('region', models.CharField(choices=[('southwest', 'southwest'), ('northwest', 'northwest'), ('northeast', 'northeast'), ('southeast', 'southeast')], max_length=15)),
                ('smoker', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('alcoholConsumer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('diphtheria', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('polio', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('measles', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('hepatitis', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('hiv_aids', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('thinness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
            ],
        ),
    ]
